@node Appendix B, Appendix A, Index, Top
@unnumbered @rmorbold{Appendix B: Translations of the Term ``Free@tie{}Software''}

@firstcopyingnotice{{The most current list of translations is
maintained at
@url{http://www.@/gnu.@/org/@/philosophy/@/fs-translations.@/html}. Please
e-mail any additional translations to
@email{web-translators@@gnu.org}.@*
@footnoterule @medskip
@noindent{This version of the list is part of @fsfstwocite}}}

@rgindex ``free software,'' unambiguous translations of
The following is a list of recommended unambiguous translations of
the term ``free software'' into various languages:@anchor{FS
Translations}
  
   @itemize @minus

@item Afrikaans: vrye sagteware
@item Albanian: software i lir@"e
@item Arabic: @lowerbox{2.7pt, @image{arabic,, 4.1mm}}
@item Belarusian: @lowerbox{3pt, @image{belarusian,, 3.8mm}}
@item Bulgarian: @lowerbox{3pt, @image{bulgarian,, 3.8mm}}
@item Catalan: programari lliure
@item Chinese: @lowerbox{0.9pt, @image{chinese-simplified,, 3.9mm}} @kern -2pt (simplified), @lowerbox{0.9pt, @image{chinese-traditional,, 3.9mm}} @kern -2pt (traditional)
@item Czech: svobodn@'y software
@item Croatian/Serbian: slobodni softver
@item Danish: fri software @emph{or} frit programmel
@item Dutch: vrije software
@item Esperanto: libera programaro
@item Estonian: vaba tarkvara
@item Farsi: @lowerbox{4.6pt, @image{farsi,, 5mm}}
@item Finnish: vapaa ohjelmisto
@item French: logiciel libre
@item German: freie Software
@item Greek: @lowerbox{3pt, @image{greek,, 3.9mm}}
@item Hungarian: szabad szoftver
@item Icelandic: frj@'als hugb@'una@dh{}ur
@item Ido: libera programaro
@item Indonesian: perangkat lunak bebas
@item Interlingua: libere programmage @emph{or} libere programmario
@item Irish: bog earra@'{@dotless{i}} saoire
@item Italian: software libero
@item Japanese: @kern -0.5pt @lowerbox{1.1pt, @image{japanese-kanji,, 3.8mm}} @emph{or} @kern -0.5pt @lowerbox{1.1pt, @image{japanese-kana,, 3.8mm}}
@item Lithuanian: laisva programin@dotaccent{e} @ogonek{i}ranga
@item Malay: perisian bebas
@item Norwegian: fri programvare
@item Polish: wolne oprogramowanie
@item Portuguese: software livre
@item Romanian: software liber
@item Russian: @lowerbox{3pt, @image{russian,, 3.8mm}}
@item Sardinian: software liberu
@item Serbian/Croatian: @lowerbox{3pt, @image{serbian-croatian,, 3.8mm}}
@item Slovak: slobodn@'y softv@'er
@item Slovenian: prosto programje
@item Spanish: software libre
@item Swahili: Programu huru za Kompyuta
@item Swedish: fri programvara, fri mjukvara
@item Tagalog: malayang software
@item Tamil: @lowerbox{3.5pt, @image{tamil,, 3.9mm}}
@item Turkish: @"ozg@"ur yaz@dotless{i}l@dotless{i}m
@item Ukrainian: @kern -1pt @lowerbox{3.1pt, @image{ukrainian,, 3.8mm}}
@item Welsh: meddalwedd rydd
@item Zulu: Isoftware Ekhululekile

@rgindex ``free software,'' unambiguous translations of
@end itemize
