@node Preface, Part One, Foreword, Top
@unnumbered Preface to the Second Edition

The second edition of @cite{Free Software, Free Society} holds updated
versions of most of the essays from the first edition, as well as many
new essays published since the first edition.

The essays about software patents are now in one section and those
about copyright in another, to set an example of not grouping together
these two laws, whose workings and effects on software are totally
different.

Another section presents the GNU licenses, with a new introduction
written with Brett Smith giving their history and the motives for each
of them. One of the essays explains why software projects should
upgrade to version 3 of the GNU General Public License.

There is now a section on issues of terminology, since the way we
describe an issue affects how people think about it.

The last two sections describe some of the traps free software
developers and users face---new ways to lose your freedom, and how to
avoid them.

We have also added an index, to complement the appendix on software.

We would like to thank Jeanne Rasata for managing the project, editing
the book, formatting the text, and creating the index. Thanks also to
Karl Berry for technical assistance with Texinfo, Brett Smith for all
other technical help and for valuable feedback, and Rob Myers for
formatting the cover.

