@node Song, Part Two, Selling, Top
@chapter The Free Software Song

@cindex Stallman, Richard
@cindex ``Free Software Song''
@cindex ``Sadi moma bela loza''
@cindex hackers
The lyrics of ``The Free Software Song'' are sung to the melody of the
Bulgarian folk song ``Sadi moma bela loza.'' To listen to a recording
of the piece accompanied by Bulgarian instruments played in
traditional style, please visit
@url{http://gnu.@/org/@/music/@/FreeSWSong.@/ogg}.
@firstcopyingnotice{{This song is in a rhythm of 7/8; those
unaccustomed to odd rhythms often take the unevenness to be a
mistake. The meter can be analyzed into three subgroups as
slow-quick-quick or 3-2-2. Such meters in Bulgarian music can often be
stretched, and some musicians analyze this song as 3-2-3 instead;
however, the last ``3'' is not as long as the first. Yves Moreau, who
collected and taught the dance, endorses the rhythm of 7.@*
@footnoterule @medskip
Copyright @copyright{} 2010 Richard Stallman@*
@indent{Richard Stallman wrote the lyrics above in 1991. This version of the score is published in @fsfstwocite}}}
@sp 1
@center @image{song-book-jutta-scrunch-crop,,3.5in}
